title: A life less complex
author: Sidney de Koning
email: me@alifelesscomplex.com
description: > # this means to ignore newlines until "baseurl:"
  A life less complex is my journey to declutter my mind, body and house. This blog started because I wanted to write about the coachings I got to deal with my AD(H)D and the things I learned there. I’ll also write about being financially independent, how to get out of financial dept, and other things that help reduce the clutter in a world where we a constantly bombarded with consumerism and social ADHD.
baseurl: "/"
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
twitter_username: sidneydekoning
instagram_username: sidneydekoning

# Build settings
markdown: kramdown
remote_theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock
