title: A life less complex
author: Sidney de Koning
email: me@alifelesscomplex.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
twitter_username: sidneydekoning
instagram_username: sidneydekoning

# Build settings
markdown: kramdown
remote_theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock
